from typing import List

import openai
import streamlit as st
from langchain.document_loaders import TextLoader
from langchain.embeddings.sentence_transformer import SentenceTransformerEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import Chroma
from openai import OpenAI

# Set the OpenAI API key. This key is retrieved from a Streamlit's secrets management system,
# which securely stores and accesses sensitive information like API keys.
openai.api_key = st.secrets["OPENAI_API_KEY"]


# Initialize an OpenAI client. This client will be used to interact with OpenAI's API.
openai_client = openai.OpenAI()


# Files names
def get_all_files_names():
    return [
    'data/txt/Exenatide Phase 1.1_0.txt',
    'data/txt/Exenatide Phase 1.1_1.txt',
    'data/txt/Exenatide Phase 1.1_2.txt',
    'data/txt/Exenatide Phase 1.2_0.txt',
    'data/txt/Exenatide Phase 1.2_1.txt',
    'data/txt/Exenatide Phase 1.2_2.txt',
    'data/txt/Exenatide Phase 1.1_3.txt',
    'data/txt/Exenatide Phase 1.2_3.txt',
    'data/txt/Exenatide Phase 1.1_4.txt',
    'data/txt/Exenatide Phase 1.1_5.txt',
    'data/txt/Exenatide Phase 1.1_6.txt',
    'data/txt/Exenatide Phase 1.1_7.txt',
    'data/txt/Exenatide Phase 1.1_8.txt',
    'data/txt/Exenatide Phase 1.1_9.txt',
    'data/txt/Exenatide Phase 1.1_10.txt',
    'data/txt/Exenatide Phase 1.1_11.txt',
    'data/txt/Exenatide Phase 1.1_12.txt',
    'data/txt/Exenatide Phase 1.1_13.txt',
    'data/txt/Exenatide Phase 1.1_14.txt',
    'data/txt/Exenatide Phase 1.1_15.txt',
    'data/txt/Exenatide Phase 1.1_16.txt',
    'data/txt/Exenatide Phase 1.1_17.txt',
    'data/txt/Exenatide Phase 1.1_18.txt',
    'data/txt/Exenatide Phase 1.1_19.txt',
    'data/txt/Exenatide Phase 1.1_20.txt',
    'data/txt/Exenatide Phase 1.1_21.txt',
    'data/txt/Exenatide Phase 1.1_22.txt',
    'data/txt/Exenatide Phase 1.1_23.txt',
    'data/txt/Exenatide Phase 1.1_24.txt',
    'data/txt/Exenatide Phase 1.1_25.txt',
    'data/txt/Exenatide Phase 1.1_26.txt',
    'data/txt/Exenatide Phase 1.1_27.txt',
    'data/txt/Exenatide Phase 1.1_28.txt',
    'data/txt/Exenatide Phase 1.1_29.txt',
    'data/txt/Exenatide Phase 1.1_30.txt',
    'data/txt/Exenatide Phase 1.1_31.txt',
    'data/txt/Exenatide Phase 1.1_32.txt',
    'data/txt/Exenatide Phase 1.1_33.txt',
    'data/txt/Exenatide Phase 1.1_34.txt',
    'data/txt/Exenatide Phase 1.1_35.txt',
    'data/txt/Exenatide Phase 1.1_36.txt',
    'data/txt/Exenatide Phase 1.1_37.txt',
    'data/txt/Exenatide Phase 1.1_38.txt',
    'data/txt/Exenatide Phase 1.1_39.txt',
    'data/txt/Exenatide Phase 1.1_40.txt',
    'data/txt/Exenatide Phase 1.1_41.txt',
    'data/txt/Exenatide Phase 1.1_42.txt',
    'data/txt/Exenatide Phase 1.1_43.txt',
    'data/txt/Exenatide Phase 1.1_44.txt',
    'data/txt/Exenatide Phase 1.1_45.txt',
    'data/txt/Exenatide Phase 1.1_46.txt',
    'data/txt/Exenatide Phase 1.1_47.txt',
    'data/txt/Exenatide Phase 1.2_4.txt',
    'data/txt/Exenatide Phase 1.2_5.txt',
    'data/txt/Exenatide Phase 1.2_6.txt',
    'data/txt/Exenatide Phase 1.2_7.txt',
    'data/txt/Exenatide Phase 1.2_8.txt',
    'data/txt/Exenatide Phase 1.2_9.txt',
    'data/txt/Exenatide Phase 1.2_10.txt',
    'data/txt/Exenatide Phase 1.2_11.txt',
    'data/txt/Exenatide Phase 1.2_12.txt',
    'data/txt/Exenatide Phase 1.2_13.txt',
    'data/txt/Exenatide Phase 1.2_14.txt',
    'data/txt/Exenatide Phase 1.2_15.txt',
    'data/txt/Exenatide Phase 1.2_16.txt',
    'data/txt/Exenatide Phase 1.2_17.txt',
    'data/txt/Exenatide Phase 1.2_18.txt',
    'data/txt/Exenatide Phase 1.2_19.txt',
    'data/txt/Exenatide Phase 1.2_20.txt',
    'data/txt/Exenatide Phase 1.2_21.txt',
    'data/txt/Exenatide Phase 1.2_22.txt',
    'data/txt/Exenatide Phase 1.2_23.txt',
    'data/txt/Exenatide Phase 1.2_24.txt',
    'data/txt/Exenatide Phase 1.2_25.txt',
    'data/txt/Exenatide Phase 1.2_26.txt',
    'data/txt/Exenatide Phase 1.2_27.txt',
    'data/txt/Exenatide Phase 1.2_28.txt',
    'data/txt/Exenatide Phase 1.2_29.txt',
    'data/txt/Exenatide Phase 1.2_30.txt',
    'data/txt/Exenatide Phase 1.2_31.txt',
    'data/txt/Exenatide Phase 1.2_32.txt',
    'data/txt/Exenatide Phase 1.2_33.txt',
    'data/txt/Exenatide Phase 1.2_34.txt',
    'data/txt/Exenatide Phase 1.2_35.txt',
    'data/txt/Exenatide Phase 1.2_36.txt',
    'data/txt/Exenatide Phase 1.2_37.txt',
    'data/txt/Exenatide Phase 1.2_38.txt',
    'data/txt/Exenatide Phase 1.2_39.txt',
    'data/txt/Exenatide Phase 1.2_40.txt',
    'data/txt/Exenatide Phase 1.2_41.txt',
    'data/txt/Exenatide Phase 1.2_42.txt',
    'data/txt/Exenatide Phase 1.2_43.txt',
    'data/txt/Exenatide Phase 1.2_44.txt',
    'data/txt/Exenatide Phase 1.2_45.txt',
    'data/txt/Exenatide Phase 1.2_46.txt',
    'data/txt/Exenatide Phase 1.2_47.txt',
    'data/txt/Exenatide Phase 1.2_48.txt',
    'data/txt/Exenatide Phase 1.2_49.txt',
    'data/txt/Exenatide Phase 1.2_50.txt',
    'data/txt/Exenatide Phase 1.2_51.txt',
    'data/txt/Exenatide Phase 1.2_52.txt',
    'data/txt/Exenatide Phase 1.2_53.txt',
    'data/txt/Exenatide Phase 1.2_54.txt',
    'data/txt/Exenatide Phase 1.2_55.txt',
    'data/txt/Exenatide Phase 2.1_0.txt',
    'data/txt/Exenatide Phase 2.1_1.txt',
    'data/txt/Exenatide Phase 2.1_2.txt',
    'data/txt/Exenatide Phase 2.1_3.txt',
    'data/txt/Exenatide Phase 2.1_4.txt',
    'data/txt/Exenatide Phase 2.1_5.txt',
    'data/txt/Exenatide Phase 2.1_6.txt',
    'data/txt/Exenatide Phase 2.1_7.txt',
    'data/txt/Exenatide Phase 2.1_8.txt',
    'data/txt/Exenatide Phase 2.1_9.txt',
    'data/txt/Exenatide Phase 2.1_10.txt',
    'data/txt/Exenatide Phase 2.1_11.txt',
    'data/txt/Exenatide Phase 2.1_12.txt',
    'data/txt/Exenatide Phase 2.1_13.txt',
    'data/txt/Exenatide Phase 2.1_14.txt',
    'data/txt/Exenatide Phase 2.1_15.txt',
    'data/txt/Exenatide Phase 2.1_16.txt',
    'data/txt/Exenatide Phase 2.1_17.txt',
    'data/txt/Exenatide Phase 2.1_18.txt',
    'data/txt/Exenatide Phase 2.1_19.txt',
    'data/txt/Exenatide Phase 2.1_20.txt',
    'data/txt/Exenatide Phase 2.1_21.txt',
    'data/txt/Exenatide Phase 2.1_22.txt',
    'data/txt/Exenatide Phase 2.1_23.txt',
    'data/txt/Exenatide Phase 2.1_24.txt',
    'data/txt/Exenatide Phase 2.1_25.txt',
    'data/txt/Exenatide Phase 2.1_26.txt',
    'data/txt/Exenatide Phase 2.1_27.txt',
    'data/txt/Exenatide Phase 2.1_28.txt',
    'data/txt/Exenatide Phase 2.1_29.txt',
    'data/txt/Exenatide Phase 2.1_30.txt',
    'data/txt/Exenatide Phase 2.1_31.txt',
    'data/txt/Exenatide Phase 2.1_32.txt',
    'data/txt/Exenatide Phase 2.1_33.txt',
    'data/txt/Exenatide Phase 2.1_34.txt',
    'data/txt/Exenatide Phase 2.1_35.txt',
    'data/txt/Exenatide Phase 2.1_36.txt',
    'data/txt/Exenatide Phase 2.1_37.txt',
    'data/txt/Exenatide Phase 2.1_38.txt',
    'data/txt/Exenatide Phase 2.1_39.txt',
    'data/txt/Exenatide Phase 2.1_40.txt',
    'data/txt/Exenatide Phase 2.1_41.txt',
    'data/txt/Exenatide Phase 2.1_42.txt',
    'data/txt/Exenatide Phase 2.1_43.txt',
    'data/txt/Exenatide Phase 2.1_44.txt',
    'data/txt/Exenatide Phase 2.1_45.txt',
    'data/txt/Exenatide Phase 2.1_46.txt',
    'data/txt/Exenatide Phase 2.1_47.txt',
    'data/txt/Exenatide Phase 2.1_48.txt',
    'data/txt/Exenatide Phase 2.1_49.txt',
    'data/txt/Exenatide Phase 2.2_0.txt',
    'data/txt/Exenatide Phase 2.2_1.txt',
    'data/txt/Exenatide Phase 2.2_2.txt',
    'data/txt/Exenatide Phase 2.2_3.txt',
    'data/txt/Exenatide Phase 2.2_4.txt',
    'data/txt/Exenatide Phase 2.2_5.txt',
    'data/txt/Exenatide Phase 2.2_6.txt',
    'data/txt/Exenatide Phase 2.2_7.txt',
    'data/txt/Exenatide Phase 2.2_8.txt',
    'data/txt/Exenatide Phase 2.2_9.txt',
    'data/txt/Exenatide Phase 2.2_10.txt',
    'data/txt/Exenatide Phase 2.2_11.txt',
    'data/txt/Exenatide Phase 2.2_12.txt',
    'data/txt/Exenatide Phase 2.2_13.txt',
    'data/txt/Exenatide Phase 2.2_14.txt',
    'data/txt/Exenatide Phase 2.2_15.txt',
    'data/txt/Exenatide Phase 2.2_16.txt',
    'data/txt/Exenatide Phase 2.2_17.txt',
    'data/txt/Exenatide Phase 2.2_18.txt',
    'data/txt/Exenatide Phase 2.2_19.txt',
    'data/txt/Exenatide Phase 2.2_20.txt',
    'data/txt/Exenatide Phase 2.2_21.txt',
    'data/txt/Exenatide Phase 2.2_22.txt',
    'data/txt/Exenatide Phase 2.2_23.txt',
    'data/txt/Exenatide Phase 2.2_24.txt',
    'data/txt/Exenatide Phase 2.2_25.txt',
    'data/txt/Exenatide Phase 2.2_26.txt',
    'data/txt/Exenatide Phase 2.2_27.txt',
    'data/txt/Exenatide Phase 2.2_28.txt',
    'data/txt/Exenatide Phase 2.2_29.txt',
    'data/txt/Exenatide Phase 2.2_30.txt',
    'data/txt/Exenatide Phase 2.2_31.txt',
    'data/txt/Exenatide Phase 2.2_32.txt',
    'data/txt/Exenatide Phase 2.2_33.txt',
    'data/txt/Exenatide Phase 2.2_34.txt',
    'data/txt/Exenatide Phase 2.2_35.txt',
    'data/txt/Exenatide Phase 2.2_36.txt',
    'data/txt/Exenatide Phase 2.2_37.txt',
    'data/txt/Exenatide Phase 2.2_38.txt',
    'data/txt/Exenatide Phase 2.2_39.txt',
    'data/txt/Exenatide Phase 2.2_40.txt',
    'data/txt/Exenatide Phase 2.2_41.txt',
    'data/txt/Exenatide Phase 2.2_42.txt',
    'data/txt/Exenatide Phase 2.2_43.txt',
    'data/txt/Exenatide Phase 2.2_44.txt',
    'data/txt/Exenatide Phase 2.2_45.txt',
    'data/txt/Exenatide Phase 2.2_46.txt',
    'data/txt/Exenatide Phase 2.2_47.txt',
    'data/txt/Exenatide Phase 2.3_0.txt',
    'data/txt/Exenatide Phase 2.3_1.txt',
    'data/txt/Exenatide Phase 2.3_2.txt',
    'data/txt/Exenatide Phase 2.3_3.txt',
    'data/txt/Exenatide Phase 2.3_4.txt',
    'data/txt/Exenatide Phase 2.3_5.txt',
    'data/txt/Exenatide Phase 2.3_6.txt',
    'data/txt/Exenatide Phase 2.3_7.txt',
    'data/txt/Exenatide Phase 2.3_8.txt',
    'data/txt/Exenatide Phase 2.3_9.txt',
    'data/txt/Exenatide Phase 2.3_10.txt',
    'data/txt/Exenatide Phase 2.3_11.txt',
    'data/txt/Exenatide Phase 2.3_12.txt',
    'data/txt/Exenatide Phase 2.3_13.txt',
    'data/txt/Exenatide Phase 2.3_14.txt',
    'data/txt/Exenatide Phase 2.3_15.txt',
    'data/txt/Exenatide Phase 2.3_16.txt',
    'data/txt/Exenatide Phase 2.3_17.txt',
    'data/txt/Exenatide Phase 2.3_18.txt',
    'data/txt/Exenatide Phase 2.3_19.txt',
    'data/txt/Exenatide Phase 2.3_20.txt',
    'data/txt/Exenatide Phase 2.3_21.txt',
    'data/txt/Exenatide Phase 2.3_22.txt',
    'data/txt/Exenatide Phase 2.3_23.txt',
    'data/txt/Exenatide Phase 2.3_24.txt',
    'data/txt/Exenatide Phase 2.3_25.txt',
    'data/txt/Exenatide Phase 2.3_26.txt',
    'data/txt/Exenatide Phase 2.3_27.txt',
    'data/txt/Exenatide Phase 2.3_28.txt',
    'data/txt/Exenatide Phase 2.3_29.txt',
    'data/txt/Exenatide Phase 2.3_30.txt',
    'data/txt/Exenatide Phase 2.3_31.txt',
    'data/txt/Exenatide Phase 2.3_32.txt',
    'data/txt/Exenatide Phase 2.3_33.txt',
    'data/txt/Exenatide Phase 2.3_34.txt',
    'data/txt/Exenatide Phase 2.3_35.txt',
    'data/txt/Exenatide Phase 2.3_36.txt',
    'data/txt/Exenatide Phase 2.3_37.txt',
    'data/txt/Exenatide Phase 2.3_38.txt',
    'data/txt/Exenatide Phase 2.3_39.txt',
    'data/txt/Exenatide Phase 2.3_40.txt',
    'data/txt/Exenatide Phase 2.3_41.txt',
    'data/txt/Exenatide Phase 2.3_42.txt',
    'data/txt/Exenatide Phase 2.3_43.txt',
    'data/txt/Exenatide Phase 2.3_44.txt',
    'data/txt/Exenatide Phase 2.3_45.txt',
    'data/txt/Exenatide Phase 2.3_46.txt',
    'data/txt/Exenatide Phase 2.4_0.txt',
    'data/txt/Exenatide Phase 2.4_1.txt',
    'data/txt/Exenatide Phase 2.4_2.txt',
    'data/txt/Exenatide Phase 2.4_3.txt',
    'data/txt/Exenatide Phase 2.4_4.txt',
    'data/txt/Exenatide Phase 2.4_5.txt',
    'data/txt/Exenatide Phase 2.4_6.txt',
    'data/txt/Exenatide Phase 2.4_7.txt',
    'data/txt/Exenatide Phase 2.4_8.txt',
    'data/txt/Exenatide Phase 2.4_9.txt',
    'data/txt/Exenatide Phase 2.4_10.txt',
    'data/txt/Exenatide Phase 2.4_11.txt',
    'data/txt/Exenatide Phase 2.4_12.txt',
    'data/txt/Exenatide Phase 2.4_13.txt',
    'data/txt/Exenatide Phase 2.4_14.txt',
    'data/txt/Exenatide Phase 2.4_15.txt',
    'data/txt/Exenatide Phase 2.4_16.txt',
    'data/txt/Exenatide Phase 2.4_17.txt',
    'data/txt/Exenatide Phase 2.4_18.txt',
    'data/txt/Exenatide Phase 2.4_19.txt',
    'data/txt/Exenatide Phase 2.4_20.txt',
    'data/txt/Exenatide Phase 2.4_21.txt',
    'data/txt/Exenatide Phase 2.4_22.txt',
    'data/txt/Exenatide Phase 2.4_23.txt',
    'data/txt/Exenatide Phase 2.4_24.txt',
    'data/txt/Exenatide Phase 2.4_25.txt',
    'data/txt/Exenatide Phase 2.4_26.txt',
    'data/txt/Exenatide Phase 2.4_27.txt',
    'data/txt/Exenatide Phase 2.4_28.txt',
    'data/txt/Exenatide Phase 2.4_29.txt',
    'data/txt/Exenatide Phase 2.4_30.txt',
    'data/txt/Exenatide Phase 2.4_31.txt',
    'data/txt/Exenatide Phase 2.4_32.txt',
    'data/txt/Exenatide Phase 2.4_33.txt',
    'data/txt/Exenatide Phase 2.4_34.txt',
    'data/txt/Exenatide Phase 2.5_0.txt',
    'data/txt/Exenatide Phase 2.5_1.txt',
    'data/txt/Exenatide Phase 2.5_2.txt',
    'data/txt/Exenatide Phase 2.5_3.txt',
    'data/txt/Exenatide Phase 2.5_4.txt',
    'data/txt/Exenatide Phase 2.5_5.txt',
    'data/txt/Exenatide Phase 2.5_6.txt',
    'data/txt/Exenatide Phase 2.5_7.txt',
    'data/txt/Exenatide Phase 2.5_8.txt',
    'data/txt/Exenatide Phase 2.5_9.txt',
    'data/txt/Exenatide Phase 2.5_10.txt',
    'data/txt/Exenatide Phase 2.5_11.txt',
    'data/txt/Exenatide Phase 2.5_12.txt',
    'data/txt/Exenatide Phase 2.5_13.txt',
    'data/txt/Exenatide Phase 2.5_14.txt',
    'data/txt/Exenatide Phase 2.5_15.txt',
    'data/txt/Exenatide Phase 2.5_16.txt',
    'data/txt/Exenatide Phase 2.5_17.txt',
    'data/txt/Exenatide Phase 2.5_18.txt',
    'data/txt/Exenatide Phase 2.5_19.txt',
    'data/txt/Exenatide Phase 2.5_20.txt',
    'data/txt/Exenatide Phase 2.5_21.txt',
    'data/txt/Exenatide Phase 2.5_22.txt',
    'data/txt/Exenatide Phase 2.5_23.txt',
    'data/txt/Exenatide Phase 2.5_24.txt',
    'data/txt/Exenatide Phase 2.5_25.txt',
    'data/txt/Exenatide Phase 2.5_26.txt',
    'data/txt/Exenatide Phase 2.5_27.txt',
    'data/txt/Exenatide Phase 2.5_28.txt',
    'data/txt/Exenatide Phase 2.5_29.txt',
    'data/txt/Exenatide Phase 2.5_30.txt',
    'data/txt/Exenatide Phase 2.5_31.txt',
    'data/txt/Exenatide Phase 2.5_32.txt',
    'data/txt/Exenatide Phase 2.5_33.txt',
    'data/txt/Exenatide Phase 2.5_34.txt',
    'data/txt/Exenatide Phase 2.5_35.txt',
    'data/txt/Exenatide Phase 2.5_36.txt',
    'data/txt/Exenatide Phase 2.5_37.txt',
    'data/txt/Exenatide Phase 2.5_38.txt',
    'data/txt/Exenatide Phase 2.5_39.txt',
    'data/txt/Exenatide Phase 2.5_40.txt',
    'data/txt/Exenatide Phase 2.5_41.txt',
    'data/txt/Exenatide Phase 2.5_42.txt',
    'data/txt/Exenatide Phase 2.5_43.txt',
    'data/txt/Exenatide Phase 2.5_44.txt',
    'data/txt/Exenatide Phase 2.5_45.txt',
    'data/txt/Exenatide Phase 2.5_46.txt',
    'data/txt/Exenatide Phase 2.5_47.txt',
    'data/txt/Exenatide Phase 2.5_48.txt',
    'data/txt/Exenatide Phase 2.5_49.txt',
    'data/txt/Exenatide Phase 2.5_50.txt',
    'data/txt/Exenatide Phase 2.5_51.txt',
    'data/txt/Exenatide Phase 2.5_52.txt',
    'data/txt/Exenatide Phase 2.5_53.txt',
    'data/txt/Exenatide Phase 2.5_54.txt',
    'data/txt/Exenatide Phase 2.5_55.txt',
    'data/txt/Exenatide Phase 2.5_56.txt',
    'data/txt/Exenatide Phase 2.5_57.txt',
    'data/txt/Exenatide Phase 2.5_58.txt',
    'data/txt/Exenatide Phase 2.5_59.txt',
    'data/txt/Exenatide Phase 2.6_0.txt',
    'data/txt/Exenatide Phase 2.6_1.txt',
    'data/txt/Exenatide Phase 2.6_2.txt',
    'data/txt/Exenatide Phase 2.6_3.txt',
    'data/txt/Exenatide Phase 2.6_4.txt',
    'data/txt/Exenatide Phase 2.6_5.txt',
    'data/txt/Exenatide Phase 2.6_6.txt',
    'data/txt/Exenatide Phase 2.6_7.txt',
    'data/txt/Exenatide Phase 2.6_8.txt',
    'data/txt/Exenatide Phase 2.6_9.txt',
    'data/txt/Exenatide Phase 2.6_10.txt',
    'data/txt/Exenatide Phase 2.6_11.txt',
    'data/txt/Exenatide Phase 2.6_12.txt',
    'data/txt/Exenatide Phase 2.6_13.txt',
    'data/txt/Exenatide Phase 2.6_14.txt',
    'data/txt/Exenatide Phase 2.6_15.txt',
    'data/txt/Exenatide Phase 2.6_16.txt',
    'data/txt/Exenatide Phase 2.6_17.txt',
    'data/txt/Exenatide Phase 2.6_18.txt',
    'data/txt/Exenatide Phase 2.6_19.txt',
    'data/txt/Exenatide Phase 2.6_20.txt',
    'data/txt/Exenatide Phase 2.6_21.txt',
    'data/txt/Exenatide Phase 2.6_22.txt',
    'data/txt/Exenatide Phase 2.6_23.txt',
    'data/txt/Exenatide Phase 2.6_24.txt',
    'data/txt/Exenatide Phase 2.6_25.txt',
    'data/txt/Exenatide Phase 2.6_26.txt',
    'data/txt/Exenatide Phase 2.6_27.txt',
    'data/txt/Exenatide Phase 2.6_28.txt',
    'data/txt/Exenatide Phase 2.6_29.txt',
    'data/txt/Exenatide Phase 2.6_30.txt',
    'data/txt/Exenatide Phase 2.6_31.txt',
    'data/txt/Exenatide Phase 2.6_32.txt',
    'data/txt/Exenatide Phase 2.6_33.txt',
    'data/txt/Exenatide Phase 2.6_34.txt',
    'data/txt/Exenatide Phase 2.6_35.txt',
    'data/txt/Exenatide Phase 2.6_36.txt',
    'data/txt/Exenatide Phase 2.6_37.txt',
    'data/txt/Exenatide Phase 2.6_38.txt',
    'data/txt/Exenatide Phase 2.6_39.txt',
    'data/txt/Exenatide Phase 2.6_40.txt',
    'data/txt/Exenatide Phase 2.6_41.txt',
    'data/txt/Exenatide Phase 2.6_42.txt',
    'data/txt/Exenatide Phase 2.6_43.txt',
    'data/txt/Exenatide Phase 2.6_44.txt',
    'data/txt/Exenatide Phase 2.6_45.txt',
    'data/txt/Exenatide Phase 2.6_46.txt',
    'data/txt/Exenatide Phase 2.6_47.txt',
    'data/txt/Exenatide Phase 2.7_0.txt',
    'data/txt/Exenatide Phase 2.7_1.txt',
    'data/txt/Exenatide Phase 2.7_2.txt',
    'data/txt/Exenatide Phase 2.7_3.txt',
    'data/txt/Exenatide Phase 2.7_4.txt',
    'data/txt/Exenatide Phase 2.7_5.txt',
    'data/txt/Exenatide Phase 2.7_6.txt',
    'data/txt/Exenatide Phase 2.7_7.txt',
    'data/txt/Exenatide Phase 2.7_8.txt',
    'data/txt/Exenatide Phase 2.7_9.txt',
    'data/txt/Exenatide Phase 2.7_10.txt',
    'data/txt/Exenatide Phase 2.7_11.txt',
    'data/txt/Exenatide Phase 2.7_12.txt',
    'data/txt/Exenatide Phase 2.7_13.txt',
    'data/txt/Exenatide Phase 2.7_14.txt',
    'data/txt/Exenatide Phase 2.7_15.txt',
    'data/txt/Exenatide Phase 2.7_16.txt',
    'data/txt/Exenatide Phase 2.7_17.txt',
    'data/txt/Exenatide Phase 2.7_18.txt',
    'data/txt/Exenatide Phase 2.7_19.txt',
    'data/txt/Exenatide Phase 2.7_20.txt',
    'data/txt/Exenatide Phase 2.7_21.txt',
    'data/txt/Exenatide Phase 2.7_22.txt',
    'data/txt/Exenatide Phase 2.7_23.txt',
    'data/txt/Exenatide Phase 2.7_24.txt',
    'data/txt/Exenatide Phase 2.7_25.txt',
    'data/txt/Exenatide Phase 2.7_26.txt',
    'data/txt/Exenatide Phase 2.7_27.txt',
    'data/txt/Exenatide Phase 2.7_28.txt',
    'data/txt/Exenatide Phase 2.7_29.txt',
    'data/txt/Exenatide Phase 2.7_30.txt',
    'data/txt/Exenatide Phase 2.7_31.txt',
    'data/txt/Exenatide Phase 2.7_32.txt',
    'data/txt/Exenatide Phase 2.7_33.txt',
    'data/txt/Exenatide Phase 2.7_34.txt',
    'data/txt/Exenatide Phase 2.7_35.txt',
    'data/txt/Exenatide Phase 2.7_36.txt',
    'data/txt/Exenatide Phase 2.7_37.txt',
    'data/txt/Exenatide Phase 2.7_38.txt',
    'data/txt/Exenatide Phase 2.7_39.txt',
    'data/txt/Exenatide Phase 2.7_40.txt',
    'data/txt/Exenatide Phase 2.7_41.txt',
    'data/txt/Exenatide Phase 2.7_42.txt',
    'data/txt/Exenatide Phase 2.7_43.txt',
    'data/txt/Exenatide Phase 2.7_44.txt',
    'data/txt/Exenatide Phase 2.7_45.txt',
    'data/txt/Exenatide Phase 2.7_46.txt',
    'data/txt/Exenatide Phase 2.7_47.txt',
    'data/txt/Exenatide Phase 2.7_48.txt',
    'data/txt/Exenatide Phase 2.7_49.txt',
    'data/txt/Exenatide Phase 2.7_50.txt',
    'data/txt/Exenatide Phase 2.7_51.txt',
    'data/txt/Exenatide Phase 3.1_0.txt',
    'data/txt/Exenatide Phase 3.1_1.txt',
    'data/txt/Exenatide Phase 3.1_2.txt',
    'data/txt/Exenatide Phase 3.1_3.txt',
    'data/txt/Exenatide Phase 3.1_4.txt',
    'data/txt/Exenatide Phase 3.1_5.txt',
    'data/txt/Exenatide Phase 3.1_6.txt',
    'data/txt/Exenatide Phase 3.1_7.txt',
    'data/txt/Exenatide Phase 3.1_8.txt',
    'data/txt/Exenatide Phase 3.1_9.txt',
    'data/txt/Exenatide Phase 3.1_10.txt',
    'data/txt/Exenatide Phase 3.1_11.txt',
    'data/txt/Exenatide Phase 3.1_12.txt',
    'data/txt/Exenatide Phase 3.1_13.txt',
    'data/txt/Exenatide Phase 3.1_14.txt',
    'data/txt/Exenatide Phase 3.1_15.txt',
    'data/txt/Exenatide Phase 3.1_16.txt',
    'data/txt/Exenatide Phase 3.1_17.txt',
    'data/txt/Exenatide Phase 3.1_18.txt',
    'data/txt/Exenatide Phase 3.1_19.txt',
    'data/txt/Exenatide Phase 3.1_20.txt',
    'data/txt/Exenatide Phase 3.1_21.txt',
    'data/txt/Exenatide Phase 3.1_22.txt',
    'data/txt/Exenatide Phase 3.1_23.txt',
    'data/txt/Exenatide Phase 3.1_24.txt',
    'data/txt/Exenatide Phase 3.1_25.txt',
    'data/txt/Exenatide Phase 3.1_26.txt',
    'data/txt/Exenatide Phase 3.1_27.txt',
    'data/txt/Exenatide Phase 3.1_28.txt',
    'data/txt/Exenatide Phase 3.1_29.txt',
    'data/txt/Exenatide Phase 3.1_30.txt',
    'data/txt/Exenatide Phase 3.1_31.txt',
    'data/txt/Exenatide Phase 3.1_32.txt',
    'data/txt/Exenatide Phase 3.1_33.txt',
    'data/txt/Exenatide Phase 3.1_34.txt',
    'data/txt/Exenatide Phase 3.1_35.txt',
    'data/txt/Exenatide Phase 3.1_36.txt',
    'data/txt/Exenatide Phase 3.1_37.txt',
    'data/txt/Exenatide Phase 3.1_38.txt',
    'data/txt/Exenatide Phase 3.1_39.txt',
    'data/txt/Exenatide Phase 3.1_40.txt',
    'data/txt/Exenatide Phase 3.1_41.txt',
    'data/txt/Exenatide Phase 3.1_42.txt',
    'data/txt/Exenatide Phase 3.1_43.txt',
    'data/txt/Exenatide Phase 3.2_0.txt',
    'data/txt/Exenatide Phase 3.2_1.txt',
    'data/txt/Exenatide Phase 3.2_2.txt',
    'data/txt/Exenatide Phase 3.2_3.txt',
    'data/txt/Exenatide Phase 3.2_4.txt',
    'data/txt/Exenatide Phase 3.2_5.txt',
    'data/txt/Exenatide Phase 3.2_6.txt',
    'data/txt/Exenatide Phase 3.2_7.txt',
    'data/txt/Exenatide Phase 3.2_8.txt',
    'data/txt/Exenatide Phase 3.2_9.txt',
    'data/txt/Exenatide Phase 3.2_10.txt',
    'data/txt/Exenatide Phase 3.2_11.txt',
    'data/txt/Exenatide Phase 3.2_12.txt',
    'data/txt/Exenatide Phase 3.2_13.txt',
    'data/txt/Exenatide Phase 3.2_14.txt',
    'data/txt/Exenatide Phase 3.2_15.txt',
    'data/txt/Exenatide Phase 3.2_16.txt',
    'data/txt/Exenatide Phase 3.2_17.txt',
    'data/txt/Exenatide Phase 3.2_18.txt',
    'data/txt/Exenatide Phase 3.2_19.txt',
    'data/txt/Exenatide Phase 3.2_20.txt',
    'data/txt/Exenatide Phase 3.2_21.txt',
    'data/txt/Exenatide Phase 3.2_22.txt',
    'data/txt/Exenatide Phase 3.2_23.txt',
    'data/txt/Exenatide Phase 3.2_24.txt',
    'data/txt/Exenatide Phase 3.2_25.txt',
    'data/txt/Exenatide Phase 3.2_26.txt',
    'data/txt/Exenatide Phase 3.2_27.txt',
    'data/txt/Exenatide Phase 3.2_28.txt',
    'data/txt/Exenatide Phase 3.2_29.txt',
    'data/txt/Exenatide Phase 3.2_30.txt',
    'data/txt/Exenatide Phase 3.2_31.txt',
    'data/txt/Exenatide Phase 3.2_32.txt',
    'data/txt/Exenatide Phase 3.2_33.txt',
    'data/txt/Exenatide Phase 3.2_34.txt',
    'data/txt/Exenatide Phase 3.2_35.txt',
    'data/txt/Exenatide Phase 3.2_36.txt',
    'data/txt/Exenatide Phase 3.2_37.txt',
    'data/txt/Exenatide Phase 3.2_38.txt',
    'data/txt/Exenatide Phase 3.2_39.txt',
    'data/txt/Exenatide Phase 3.2_40.txt',
    'data/txt/Exenatide Phase 3.2_41.txt',
    'data/txt/Exenatide Phase 3.2_42.txt',
    'data/txt/Exenatide Phase 3.2_43.txt',
    'data/txt/Exenatide Phase 3.2_44.txt',
    'data/txt/Exenatide Phase 3.2_45.txt',
    'data/txt/Exenatide Phase 3.2_46.txt',
    'data/txt/Exenatide Phase 3.2_47.txt',
    'data/txt/Exenatide Phase 3.2_48.txt',
    'data/txt/Exenatide Phase 3.2_49.txt',
    'data/txt/Exenatide Phase 3.2_50.txt',
    'data/txt/Exenatide Phase 3.3_0.txt',
    'data/txt/Exenatide Phase 3.3_1.txt',
    'data/txt/Exenatide Phase 3.3_2.txt',
    'data/txt/Exenatide Phase 3.3_3.txt',
    'data/txt/Exenatide Phase 3.3_4.txt',
    'data/txt/Exenatide Phase 3.3_5.txt',
    'data/txt/Exenatide Phase 3.3_6.txt',
    'data/txt/Exenatide Phase 3.3_7.txt',
    'data/txt/Exenatide Phase 3.3_8.txt',
    'data/txt/Exenatide Phase 3.3_9.txt',
    'data/txt/Exenatide Phase 3.3_10.txt',
    'data/txt/Exenatide Phase 3.3_11.txt',
    'data/txt/Exenatide Phase 3.3_12.txt',
    'data/txt/Exenatide Phase 3.3_13.txt',
    'data/txt/Exenatide Phase 3.3_14.txt',
    'data/txt/Exenatide Phase 3.3_15.txt',
    'data/txt/Exenatide Phase 3.3_16.txt',
    'data/txt/Exenatide Phase 3.3_17.txt',
    'data/txt/Exenatide Phase 3.3_18.txt',
    'data/txt/Exenatide Phase 3.3_19.txt',
    'data/txt/Exenatide Phase 3.3_20.txt',
    'data/txt/Exenatide Phase 3.3_21.txt',
    'data/txt/Exenatide Phase 3.3_22.txt',
    'data/txt/Exenatide Phase 3.3_23.txt',
    'data/txt/Exenatide Phase 3.3_24.txt',
    'data/txt/Exenatide Phase 3.3_25.txt',
    'data/txt/Exenatide Phase 3.3_26.txt',
    'data/txt/Exenatide Phase 3.3_27.txt',
    'data/txt/Exenatide Phase 3.3_28.txt',
    'data/txt/Exenatide Phase 3.3_29.txt',
    'data/txt/Exenatide Phase 3.3_30.txt',
    'data/txt/Exenatide Phase 3.3_31.txt',
    'data/txt/Exenatide Phase 3.3_32.txt',
    'data/txt/Exenatide Phase 3.3_33.txt',
    'data/txt/Exenatide Phase 3.3_34.txt',
    'data/txt/Exenatide Phase 3.3_35.txt',
    'data/txt/Exenatide Phase 3.3_36.txt',
    'data/txt/Exenatide Phase 3.3_37.txt',
    'data/txt/Exenatide Phase 3.3_38.txt',
    'data/txt/Exenatide Phase 3.3_39.txt',
    'data/txt/Exenatide Phase 3.3_40.txt',
    'data/txt/Exenatide Phase 3.3_41.txt',
    'data/txt/Exenatide Phase 3.3_42.txt',
    'data/txt/Exenatide Phase 3.3_43.txt',
    'data/txt/Exenatide Phase 3.3_44.txt',
    'data/txt/Exenatide Phase 3.3_45.txt',
    'data/txt/Exenatide Phase 3.3_46.txt',
    'data/txt/Exenatide Phase 3.3_47.txt',
    'data/txt/Exenatide Phase 3.3_48.txt',
    'data/txt/Exenatide Phase 3.3_49.txt',
    'data/txt/Exenatide Phase 3.3_50.txt',
    'data/txt/Exenatide Phase 3.3_51.txt',
    'data/txt/Exenatide Phase 3.3_52.txt',
    'data/txt/Exenatide Phase 3.3_53.txt',
    'data/txt/Exenatide Phase 3.3_54.txt',
    'data/txt/Exenatide Phase 3.3_55.txt',
    'data/txt/Exenatide Phase 3.3_56.txt',
    'data/txt/Exenatide Phase 3.3_57.txt',
    'data/txt/Exenatide Phase 3.3_58.txt',
    'data/txt/Exenatide Phase 3.3_59.txt',
    'data/txt/Exenatide Phase 3.3_60.txt',
    'data/txt/Exenatide Phase 3.3_61.txt',
    'data/txt/Exenatide Phase 3.3_62.txt',
    'data/txt/Exenatide Phase 3.3_63.txt',
    'data/txt/Exenatide Phase 3.3_64.txt',
    'data/txt/Exenatide Phase 3.3_65.txt',
    'data/txt/Exenatide Phase 3.3_66.txt',
    'data/txt/Exenatide Phase 3.3_67.txt',
    'data/txt/Exenatide Phase 3.4_0.txt',
    'data/txt/Exenatide Phase 3.4_1.txt',
    'data/txt/Exenatide Phase 3.4_2.txt',
    'data/txt/Exenatide Phase 3.4_3.txt',
    'data/txt/Exenatide Phase 3.4_4.txt',
    'data/txt/Exenatide Phase 3.4_5.txt',
    'data/txt/Exenatide Phase 3.4_6.txt',
    'data/txt/Exenatide Phase 3.4_7.txt',
    'data/txt/Exenatide Phase 3.4_8.txt',
    'data/txt/Exenatide Phase 3.4_9.txt',
    'data/txt/Exenatide Phase 3.4_10.txt',
    'data/txt/Exenatide Phase 3.4_11.txt',
    'data/txt/Exenatide Phase 3.4_12.txt',
    'data/txt/Exenatide Phase 3.4_13.txt',
    'data/txt/Exenatide Phase 3.4_14.txt',
    'data/txt/Exenatide Phase 3.4_15.txt',
    'data/txt/Exenatide Phase 3.4_16.txt',
    'data/txt/Exenatide Phase 3.4_17.txt',
    'data/txt/Exenatide Phase 3.4_18.txt',
    'data/txt/Exenatide Phase 3.4_19.txt',
    'data/txt/Exenatide Phase 3.4_20.txt',
    'data/txt/Exenatide Phase 3.4_21.txt',
    'data/txt/Exenatide Phase 3.4_22.txt',
    'data/txt/Exenatide Phase 3.4_23.txt',
    'data/txt/Exenatide Phase 3.4_24.txt',
    'data/txt/Exenatide Phase 3.4_25.txt',
    'data/txt/Exenatide Phase 3.4_26.txt',
    'data/txt/Exenatide Phase 3.4_27.txt',
    'data/txt/Exenatide Phase 3.4_28.txt',
    'data/txt/Exenatide Phase 3.4_29.txt',
    'data/txt/Exenatide Phase 3.4_30.txt',
    'data/txt/Exenatide Phase 3.4_31.txt',
    'data/txt/Exenatide Phase 3.4_32.txt',
    'data/txt/Exenatide Phase 3.4_33.txt',
    'data/txt/Exenatide Phase 3.4_34.txt',
    'data/txt/Exenatide Phase 3.4_35.txt',
    'data/txt/Exenatide Phase 3.4_36.txt',
    'data/txt/Exenatide Phase 3.4_37.txt',
    'data/txt/Exenatide Phase 3.4_38.txt',
    'data/txt/Exenatide Phase 3.4_39.txt',
    'data/txt/Exenatide Phase 3.4_40.txt',
    'data/txt/Exenatide Phase 3.4_41.txt',
    'data/txt/Exenatide Phase 3.5_0.txt',
    'data/txt/Exenatide Phase 3.5_1.txt',
    'data/txt/Exenatide Phase 3.5_2.txt',
    'data/txt/Exenatide Phase 3.5_3.txt',
    'data/txt/Exenatide Phase 3.5_4.txt',
    'data/txt/Exenatide Phase 3.5_5.txt',
    'data/txt/Exenatide Phase 3.5_6.txt',
    'data/txt/Exenatide Phase 3.5_7.txt',
    'data/txt/Exenatide Phase 3.5_8.txt',
    'data/txt/Exenatide Phase 3.5_9.txt',
    'data/txt/Exenatide Phase 3.5_10.txt',
    'data/txt/Exenatide Phase 3.5_11.txt',
    'data/txt/Exenatide Phase 3.5_12.txt',
    'data/txt/Exenatide Phase 3.5_13.txt',
    'data/txt/Exenatide Phase 3.5_14.txt',
    'data/txt/Exenatide Phase 3.5_15.txt',
    'data/txt/Exenatide Phase 3.5_16.txt',
    'data/txt/Exenatide Phase 3.5_17.txt',
    'data/txt/Exenatide Phase 3.5_18.txt',
    'data/txt/Exenatide Phase 3.5_19.txt',
    'data/txt/Exenatide Phase 3.5_20.txt',
    'data/txt/Exenatide Phase 3.5_21.txt',
    'data/txt/Exenatide Phase 3.5_22.txt',
    'data/txt/Exenatide Phase 3.5_23.txt',
    'data/txt/Exenatide Phase 3.5_24.txt',
    'data/txt/Exenatide Phase 3.5_25.txt',
    'data/txt/Exenatide Phase 3.5_26.txt',
    'data/txt/Exenatide Phase 3.5_27.txt',
    'data/txt/Exenatide Phase 3.5_28.txt',
    'data/txt/Exenatide Phase 3.5_29.txt',
    'data/txt/Exenatide Phase 3.5_30.txt',
    'data/txt/Exenatide Phase 3.5_31.txt',
    'data/txt/Exenatide Phase 3.5_32.txt',
    'data/txt/Exenatide Phase 3.5_33.txt',
    'data/txt/Exenatide Phase 3.5_34.txt',
    'data/txt/Exenatide Phase 3.5_35.txt',
    'data/txt/Exenatide Phase 3.5_36.txt',
    'data/txt/Exenatide Phase 3.5_37.txt',
    'data/txt/Exenatide Phase 3.5_38.txt',
    'data/txt/Exenatide Phase 3.5_39.txt',
    'data/txt/Exenatide Phase 3.5_40.txt',
    'data/txt/Exenatide Phase 3.5_41.txt',
    'data/txt/Exenatide Phase 3.5_42.txt',
    'data/txt/Exenatide Phase 3.5_43.txt',
    'data/txt/Exenatide Phase 3.5_44.txt',
    'data/txt/Exenatide Phase 3.5_45.txt',
    'data/txt/Exenatide Phase 3.5_46.txt',
    'data/txt/Exenatide Phase 3.5_47.txt',
    'data/txt/Exenatide Phase 3.5_48.txt',
    'data/txt/Exenatide Phase 3.5_49.txt',
    'data/txt/Exenatide Phase 3.5_50.txt',
    'data/txt/Exenatide Phase 3.5_51.txt',
    'data/txt/Exenatide Phase 3.5_52.txt',
    'data/txt/Exenatide Phase 3.5_53.txt',
    'data/txt/Exenatide Phase 3.5_54.txt',
    'data/txt/Exenatide Phase 3.5_55.txt',
    'data/txt/Exenatide Phase 3.5_56.txt',
    'data/txt/Exenatide Phase 3.5_57.txt',
    'data/txt/Exenatide Phase 3.5_58.txt',
    'data/txt/Exenatide Phase 3.5_59.txt',
    'data/txt/Exenatide Phase 3.6_0.txt',
    'data/txt/Exenatide Phase 3.6_1.txt',
    'data/txt/Exenatide Phase 3.6_2.txt',
    'data/txt/Exenatide Phase 3.6_3.txt',
    'data/txt/Exenatide Phase 3.6_4.txt',
    'data/txt/Exenatide Phase 3.6_5.txt',
    'data/txt/Exenatide Phase 3.6_6.txt',
    'data/txt/Exenatide Phase 3.6_7.txt',
    'data/txt/Exenatide Phase 3.6_8.txt',
    'data/txt/Exenatide Phase 3.6_9.txt',
    'data/txt/Exenatide Phase 3.6_10.txt',
    'data/txt/Exenatide Phase 3.6_11.txt',
    'data/txt/Exenatide Phase 3.6_12.txt',
    'data/txt/Exenatide Phase 3.6_13.txt',
    'data/txt/Exenatide Phase 3.6_14.txt',
    'data/txt/Exenatide Phase 3.6_15.txt',
    'data/txt/Exenatide Phase 3.6_16.txt',
    'data/txt/Exenatide Phase 3.6_17.txt',
    'data/txt/Exenatide Phase 3.6_18.txt',
    'data/txt/Exenatide Phase 3.6_19.txt',
    'data/txt/Exenatide Phase 3.6_20.txt',
    'data/txt/Exenatide Phase 3.6_21.txt',
    'data/txt/Exenatide Phase 3.6_22.txt',
    'data/txt/Exenatide Phase 3.6_23.txt',
    'data/txt/Exenatide Phase 3.6_24.txt',
    'data/txt/Exenatide Phase 3.6_25.txt',
    'data/txt/Exenatide Phase 3.6_26.txt',
    'data/txt/Exenatide Phase 3.6_27.txt',
    'data/txt/Exenatide Phase 3.6_28.txt',
    'data/txt/Exenatide Phase 3.6_29.txt',
    'data/txt/Exenatide Phase 3.6_30.txt',
    'data/txt/Exenatide Phase 3.6_31.txt',
    'data/txt/Exenatide Phase 3.6_32.txt',
    'data/txt/Exenatide Phase 3.6_33.txt',
    'data/txt/Exenatide Phase 3.6_34.txt',
    'data/txt/Exenatide Phase 3.6_35.txt',
    'data/txt/Exenatide Phase 3.6_36.txt',
    'data/txt/Exenatide Phase 3.6_37.txt',
    'data/txt/Exenatide Phase 3.6_38.txt',
    'data/txt/Exenatide Phase 3.6_39.txt',
    'data/txt/Exenatide Phase 3.6_40.txt',
    'data/txt/Exenatide Phase 3.6_41.txt',
    'data/txt/Exenatide Phase 3.6_42.txt',
    'data/txt/Exenatide Phase 3.6_43.txt',
    'data/txt/Exenatide Phase 3.6_44.txt',
    'data/txt/Exenatide Phase 3.6_45.txt',
    'data/txt/Exenatide Phase 3.6_46.txt',
    'data/txt/Exenatide Phase 3.6_47.txt',
    'data/txt/Exenatide Phase 3.6_48.txt',
    'data/txt/Exenatide Phase 3.6_49.txt',
    'data/txt/Exenatide Phase 3.6_50.txt',
    'data/txt/Exenatide Phase 3.6_51.txt',
    'data/txt/Exenatide Phase 3.6_52.txt',
    'data/txt/Exenatide Phase 3.7_0.txt',
    'data/txt/Exenatide Phase 3.7_1.txt',
    'data/txt/Exenatide Phase 3.7_2.txt',
    'data/txt/Exenatide Phase 3.7_3.txt',
    'data/txt/Exenatide Phase 3.7_4.txt',
    'data/txt/Exenatide Phase 3.7_5.txt',
    'data/txt/Exenatide Phase 3.7_6.txt',
    'data/txt/Exenatide Phase 3.7_7.txt',
    'data/txt/Exenatide Phase 3.7_8.txt',
    'data/txt/Exenatide Phase 3.7_9.txt',
    'data/txt/Exenatide Phase 3.7_10.txt',
    'data/txt/Exenatide Phase 3.7_11.txt',
    'data/txt/Exenatide Phase 3.7_12.txt',
    'data/txt/Exenatide Phase 3.7_13.txt',
    'data/txt/Exenatide Phase 3.7_14.txt',
    'data/txt/Exenatide Phase 3.7_15.txt',
    'data/txt/Exenatide Phase 3.7_16.txt',
    'data/txt/Exenatide Phase 3.7_17.txt',
    'data/txt/Exenatide Phase 3.7_18.txt',
    'data/txt/Exenatide Phase 3.7_19.txt',
    'data/txt/Exenatide Phase 3.7_20.txt',
    'data/txt/Exenatide Phase 3.7_21.txt',
    'data/txt/Exenatide Phase 3.7_22.txt',
    'data/txt/Exenatide Phase 3.7_23.txt',
    'data/txt/Exenatide Phase 3.7_24.txt',
    'data/txt/Exenatide Phase 3.7_25.txt',
    'data/txt/Exenatide Phase 3.7_26.txt',
    'data/txt/Exenatide Phase 3.7_27.txt',
    'data/txt/Exenatide Phase 3.7_28.txt',
    'data/txt/Exenatide Phase 3.7_29.txt',
    'data/txt/Exenatide Phase 3.7_30.txt',
    'data/txt/Exenatide Phase 3.7_31.txt',
    'data/txt/Exenatide Phase 3.7_32.txt',
    'data/txt/Exenatide Phase 3.7_33.txt',
    'data/txt/Exenatide Phase 3.7_34.txt',
    'data/txt/Exenatide Phase 3.7_35.txt',
    'data/txt/Exenatide Phase 3.7_36.txt',
    'data/txt/Exenatide Phase 3.7_37.txt',
    'data/txt/Exenatide Phase 3.7_38.txt',
    'data/txt/Exenatide Phase 3.7_39.txt',
    'data/txt/Exenatide Phase 3.7_40.txt',
    'data/txt/Exenatide Phase 3.7_41.txt',
    'data/txt/Exenatide Phase 3.7_42.txt',
    'data/txt/Exenatide Phase 3.7_43.txt',
    'data/txt/Exenatide Phase 3.7_44.txt',
    'data/txt/Exenatide Phase 3.7_45.txt',
    'data/txt/Exenatide Phase 3.7_46.txt',
    'data/txt/Exenatide Phase 3.7_47.txt',
    'data/txt/Exenatide Phase 3.7_48.txt',
    'data/txt/Exenatide Phase 3.7_49.txt',
    'data/txt/Exenatide Phase 3.7_50.txt',
    'data/txt/Exenatide Phase 3.7_51.txt',
    'data/txt/Exenatide Phase 3.7_52.txt',
    'data/txt/Exenatide Phase 3.7_53.txt',
    'data/txt/Exenatide Phase 3.7_54.txt',
    'data/txt/Exenatide Phase 3.7_55.txt',
    'data/txt/Exenatide Phase 3.7_56.txt',
    'data/txt/Exenatide Phase 3.7_57.txt',
    'data/txt/Exenatide Phase 3.7_58.txt',
    'data/txt/Exenatide Phase 3.7_59.txt',
    'data/txt/Exenatide Phase 3.7_60.txt',
    'data/txt/Exenatide Phase 3.7_61.txt',
    'data/txt/Exenatide Phase 3.7_62.txt',
    'data/txt/Exenatide Phase 3.7_63.txt',
    'data/txt/Exenatide Phase 3.7_64.txt',
    'data/txt/Exenatide Phase 3.7_65.txt',
    'data/txt/Exenatide Phase 3.7_66.txt',
    'data/txt/Exenatide Phase 3.7_67.txt',
    'data/txt/Exenatide Phase 3.7_68.txt',
    'data/txt/Exenatide Phase 3.7_69.txt',
    'data/txt/Exenatide Phase 3.7_70.txt',
    'data/txt/Exenatide Phase 3.7_71.txt',
    'data/txt/Exenatide Phase 3.7_72.txt',
    'data/txt/Exenatide Phase 3.7_73.txt'
]


def build_chromadb(list_files: List[str]) -> Chroma:
    """
    Builds a Chroma database from a list of text files.

    The function reads the content of each file, splits the text into chunks,
    applies embeddings, and loads the data into a Chroma database.

    Args:
    list_files (List[str]): A list of file names to be loaded.

    Returns:
    Chroma: An instance of the Chroma database populated with the processed documents.
    """

    # Initialize an empty list to hold all documents
    file_names = list_files  # List of file names provided as input

    all_documents = []  # List to store all loaded documents

    # Iterate over each file and load its contents
    for file_name in file_names:
        loader = TextLoader(file_name)  # Initialize a text loader for the file
        documents = loader.load()  # Load the contents of the file
        all_documents.extend(documents)  # Add the loaded documents to the list

    # Split the loaded documents into chunks
    # Assuming a character-based text splitter
    text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
    docs = text_splitter.split_documents(all_documents)  # Split documents into chunks

    # Create the open-source embedding function
    # Using a pre-trained sentence transformer model for embeddings
    embedding_function = SentenceTransformerEmbeddings(model_name="all-MiniLM-L6-v2")

    # Load the documents into Chroma
    db = Chroma.from_documents(
        docs, embedding_function
    )  # Create Chroma DB from documents

    return db


def load_vector_db(path_to_vectordb: str) -> Chroma:
    embedding_function = SentenceTransformerEmbeddings(model_name="all-MiniLM-L6-v2")
    loaded_db = Chroma(persist_directory=path_to_vectordb, embedding_function=embedding_function)
    return loaded_db


def rag(
    query: str, retrieved_documents: List[str], model: str = "gpt-3.5-turbo"
) -> str:
    """
    Generates a response to a query using a Retrieve-And-Generate (RAG) approach with OpenAI's GPT model.

    This function takes a user query and a list of retrieved documents relevant to the query,
    then uses the specified GPT model to generate a response based on this information.

    Args:
    query (str): The user's query or question.
    retrieved_documents (List[str]): A list of documents (strings) retrieved as relevant to the query.
    model (str, optional): The name of the GPT model to use. Defaults to "gpt-3.5-turbo".

    Returns:
    str: The generated response from the model.
    """

    # Join the retrieved documents into a single string, separated by double newlines
    information = "\n\n".join(retrieved_documents)

    # Prepare the messages to be sent to the model
    messages = [
        {
            "role": "system",
            "content": (
                "You are a helpful expert assistant. "
                "You will be shown the user's question, and the relevant information from the instructions. "
                "Answer the user's question using only this information."
            ),
        },
        {
            "role": "user",
            "content": f"Question: {query}. \n Information: {information}",
        },
    ]

    # Generate a response using the OpenAI GPT model
    response = openai_client.chat.completions.create(
        model=model,
        messages=messages,
    )

    # Extract and return the content of the response
    content = response.choices[0].message.content
    return content
